### PR TITLE
Only run the release action when the latest commit message contains `[ci]`

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Eg
- [ci] version bump
- run [ci]

Or whatever you want, as long as it contains `[ci]`

### CODE REVIEW

**Comment by exconvinced** [comment]
Gotcha! I'll keep this in mind. Appreciate this!

**Comment by ArjixWasTaken** [comment]
lmao I think it ran for this PR bc the commit description has `[ci]` in it
image

**Comment by ArjixWasTaken** [comment]
so you can have that tag in the commit description, so it doesn't make the commit title ugly or whatever

**Comment by ArjixWasTaken** [comment]
actually it is weird

**Comment by exconvinced** [comment]
I noticed that too. The zip file suddenly become 65.5 KB *panic*

Edit: my bad, i accidentally deleted the run command for downloading dependencies.

**Pull request merged**
